name: Deploy Sphinx documentation to Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
          python_version: 3.11
          checkout: true
      - name: Copy folder to deployment artifact
        run: cp -r ./assets ${{ steps.deployment.outputs.artifact }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
          force_orphan: true
