name: Publish executable

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3

    - run: pip install -e .[publish]
    - run: pip list
    - run: python build_watchdog.py
    # Verify the executable runs
    - run: copy examples/example_watch_config_no_webhook.yml ./dist/
    - run: set WATCH_CONFIG=dist/example_watch_config_no_webhook.yml
    - run: dir dist
    - run: dist/aind-watchdog-service.exe
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*