name: Publish executable

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3

    - run: pip install -e .
    - run: pip install -U pyinstaller==6.6.0
    - run: pyinstaller src/aind_watchdog_service/main.py --onefile --noconsole  -n aind-watchdog-service -i src/aind_watchdog_service/icon/watchdog.ico --clean
    # Verify the executable runs
    - run: copy examples/example_watch_config_no_webhook.yml ./dist/
    - run: set WATCH_CONFIG=dist/example_watch_config_no_webhook.yml
    - run: dir dist
    - run: dist/aind-watchdog-service.exe
    # - uses: actions/upload-artifact@v4
    #   with:
    #     path: dist/*